language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements/test.txt

script: coverage run --source='.' manage.py test send --settings=settings.test

after_success:
  - coverage report
  - coveralls