db:
  restart: always
  image: postgres
  volumes:
    - db_data:/var/lib/postgresql/data

web:
  restart: always
  build: .
  volumes:
    - .:/code
  command: /usr/local/bin/gunicorn --bind=0.0.0.0:8000 --workers=4 backend.wsgi
  environment:
    - DJANGO_SETTINGS_MODULE=settings.production
  links:
    - db

nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./dist:/tmp/app
  links:
    - web:web
