# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-08 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='uuid',
        ),
    ]
