# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=16383, verbose_name='Note')),
                ('alias', models.CharField(blank=True, max_length=63, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.User')),
            ],
            options={
                'db_table': 'note',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traceback', models.TextField(max_length=1023)),
                ('info', models.TextField(max_length=255)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.User')),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-date_create'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set([('owner', 'alias')]),
        ),
    ]
