# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 10:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=8191)),
                ('alias', models.CharField(default=utils.get_alias, max_length=63)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-created'],
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traceback', models.TextField()),
                ('info', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-created'],
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(default=utils.gen_key, max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='app.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.User'),
        ),
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.User'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set([('owner', 'alias')]),
        ),
    ]
