# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8191)),
            ],
            options={
                'db_table': 'notebook',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.NoteBook'),
        ),
    ]
